const postList = {
  data: [
    {
      owner: {
        id: "6wy6UNkZueJfIUfq88d5",
        picture: "https://randomuser.me/api/portraits/women/32.jpg",
        firstName: "Melanie",
        email: "melanie.pilz@example.com",
        title: "miss",
        lastName: "Pilz",
      },
      id: "43cuR7ZUPkwQp8GU7u3f",
      image: "https://img.dummyapi.io/photo-1564849444446-f876dcef378e.jpg",
      publishDate: "2020-05-20T18:51:23.478Z",
      text: "A feral cat short-fur gray and orange cat on green grass during daytime",
      tags: ["plant", "mammal", "pet"],
      link: null,
      likes: 40,
    },
    {
      owner: {
        id: "6wy6UNkZueJfIUfq88d5",
        picture: "https://randomuser.me/api/portraits/women/32.jpg",
        firstName: "Melanie",
        email: "melanie.pilz@example.com",
        title: "miss",
        lastName: "Pilz",
      },
      id: "PCTI6cyhd3y5q1Z0YlmA",
      image: "https://img.dummyapi.io/photo-1579178460072-07b6cebedf5f.jpg",
      publishDate: "2020-05-16T02:42:34.573Z",
      text: "Alaskan Malamute black and white wolf",
      tags: ["dog", "canine", "animal"],
      link: null,
      likes: 22,
    },
    {
      owner: {
        id: "6wy6UNkZueJfIUfq88d5",
        picture: "https://randomuser.me/api/portraits/women/32.jpg",
        firstName: "Melanie",
        email: "melanie.pilz@example.com",
        title: "miss",
        lastName: "Pilz",
      },
      id: "AZdOcxJ279XxJ3KYPePC",
      image: "https://img.dummyapi.io/photo-1516286171179-d00a36a2bbfa.jpg",
      publishDate: "2020-05-12T04:46:45.276Z",
      text: "long-coated white dog",
      tags: ["dog", "canine", "grey"],
      link: null,
      likes: 44,
    },
    {
      owner: {
        id: "6wy6UNkZueJfIUfq88d5",
        picture: "https://randomuser.me/api/portraits/women/32.jpg",
        firstName: "Melanie",
        email: "melanie.pilz@example.com",
        title: "miss",
        lastName: "Pilz",
      },
      id: "4XotWhNPx0DUEKQrsC6V",
      image: "https://img.dummyapi.io/photo-1571164712078-972f26d5144d.jpg",
      publishDate: "2020-05-05T15:34:08.456Z",
      text: "grayscale photography of boy running on shore beside dog",
      tags: ["ocean", "nature", "water"],
      link: "https://www.instagram.com/ilyuza.mif/",
      likes: 13,
    },
    {
      owner: {
        id: "6wy6UNkZueJfIUfq88d5",
        picture: "https://randomuser.me/api/portraits/women/32.jpg",
        firstName: "Melanie",
        email: "melanie.pilz@example.com",
        title: "miss",
        lastName: "Pilz",
      },
      id: "WjfVGFvUEHM9fD3fl2FY",
      image: "https://img.dummyapi.io/photo-1514070243690-479941916a51.jpg",
      publishDate: "2020-04-08T03:33:07.971Z",
      text: "short-coated white and black dog on sofa",
      tags: ["dog", "animal", "canine"],
      link: "https://jordanmadrid.myportfolio.com/",
      likes: 21,
    },
    {
      owner: {
        id: "6wy6UNkZueJfIUfq88d5",
        picture: "https://randomuser.me/api/portraits/women/32.jpg",
        firstName: "Melanie",
        email: "melanie.pilz@example.com",
        title: "miss",
        lastName: "Pilz",
      },
      id: "W6o1P7bzlELurdVpRGlB",
      image: "https://img.dummyapi.io/photo-1512704805517-9825f6d4c1bf.jpg",
      publishDate: "2020-04-01T11:52:12.350Z",
      text: "High Park dog walking in Toronto’s High Park. man walking on street with his dogs",
      tags: ["road", "nature", "toronto"],
      link: "http://www.jeffesmithphotography.com",
      likes: 25,
    },
    {
      owner: {
        id: "6wy6UNkZueJfIUfq88d5",
        picture: "https://randomuser.me/api/portraits/women/32.jpg",
        firstName: "Melanie",
        email: "melanie.pilz@example.com",
        title: "miss",
        lastName: "Pilz",
      },
      id: "uWUwgWcx3MgUauuE7rdZ",
      image: "https://img.dummyapi.io/photo-1509924295413-6722539acbb3.jpg",
      publishDate: "2020-03-20T16:23:18.395Z",
      text: "@adventure.yuki bird watching black dog running near body of water",
      tags: ["dog", "canine", "pet"],
      link: null,
      likes: 39,
    },
    {
      owner: {
        id: "6wy6UNkZueJfIUfq88d5",
        picture: "https://randomuser.me/api/portraits/women/32.jpg",
        firstName: "Melanie",
        email: "melanie.pilz@example.com",
        title: "miss",
        lastName: "Pilz",
      },
      id: "TqCrDH8PSoKx8fNrqxAz",
      image: "https://img.dummyapi.io/photo-1560313304-a30d22919658.jpg",
      publishDate: "2020-02-07T19:49:01.151Z",
      text: "short-coated tan dog",
      tags: ["dog", "animal", "puppy"],
      link: "https://www.instagram.com/p/BdXpYVJno6H/",
      likes: 36,
    },
    {
      owner: {
        id: "6wy6UNkZueJfIUfq88d5",
        picture: "https://randomuser.me/api/portraits/women/32.jpg",
        firstName: "Melanie",
        email: "melanie.pilz@example.com",
        title: "miss",
        lastName: "Pilz",
      },
      id: "5wTsikPxbR0z4eBt6gHX",
      image: "https://img.dummyapi.io/photo-1495096848005-d77907109d78.jpg",
      publishDate: "2020-01-12T19:04:12.047Z",
      text: "In my recent visit to Ljubljana I photographed this humble Dalmatian called Buddha, whose owner was the dad of the girl in the distance. The father explained to us that his daughter was autist and that dogs are commonly used to help coping with mental health challenges. I believe that one can see in Buddha’s deep eyes his patience and respect towards the family. Harley Quinn great dane",
      tags: ["dog", "animal", "black-and-white"],
      link: null,
      likes: 250,
    },
    {
      owner: {
        id: "6wy6UNkZueJfIUfq88d5",
        picture: "https://randomuser.me/api/portraits/women/32.jpg",
        firstName: "Melanie",
        email: "melanie.pilz@example.com",
        title: "miss",
        lastName: "Pilz",
      },
      id: "H52DXsAWPlEjTs3EqQAb",
      image: "https://img.dummyapi.io/photo-1569285105804-efe0ac1e44ea.jpg",
      publishDate: "2020-01-05T16:19:06.811Z",
      text: "selective focus photography of two brown and white dogs with collar",
      tags: ["dog", "animal", "canine"],
      link: "http://www.instagram.com/spencerdavisphoto",
      likes: 30,
    },
    {
      owner: {
        id: "6wy6UNkZueJfIUfq88d5",
        picture: "https://randomuser.me/api/portraits/women/32.jpg",
        firstName: "Melanie",
        email: "melanie.pilz@example.com",
        title: "miss",
        lastName: "Pilz",
      },
      id: "r8eGS00LsMOLkIKGvBVB",
      image: "https://img.dummyapi.io/photo-1573571945929-aa72904b953f.jpg",
      publishDate: "2020-01-05T03:56:26.373Z",
      text: "selective focus photo of white and black dog on beach",
      tags: ["dog", "animal", "pet"],
      link: null,
      likes: 9,
    },
    {
      owner: {
        id: "6wy6UNkZueJfIUfq88d5",
        picture: "https://randomuser.me/api/portraits/women/32.jpg",
        firstName: "Melanie",
        email: "melanie.pilz@example.com",
        title: "miss",
        lastName: "Pilz",
      },
      id: "ZPD9jC72sh1IAFcbApVy",
      image: "https://img.dummyapi.io/photo-1577447073438-c6b887157c24.jpg",
      publishDate: "2020-01-01T11:08:48.493Z",
      text: "brown Cavalier King Charles Spaniel dogs with Rudolph's ears   three brown Cocker Spaniel dogs",
      tags: ["dog", "canine", "animal"],
      link: "https://flouffy.com/",
      likes: 50,
    },
  ],
  total: 12,
  page: 0,
  limit: 20,
  offset: 0,
};

export default postList;
